org: hopeshare
app: serverless-crud
service: serverless-crud
frameworkVersion: "4"

custom:
  usersTableName: hopeshare-users
  campanhaTableName: hopeshare-campanha
  depositRequestTableName: hopeshare-deposit-request
  validationUserTableName: hopeshare-validation-user
  donationTableName: hopeshare-donation
  reportsTableName: hopeshare-reports
  configReceiptTableName: hopeshare-config-receipt
  bankTableName: hopeshare-bank

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [CampanhaTable, Arn]
            - Fn::GetAtt: [DepositRequestTable, Arn]
            - Fn::GetAtt: [ValidationUserTable, Arn]
            - Fn::GetAtt: [DonationTable, Arn]
            - Fn::GetAtt: [ReportsTable, Arn]
            - Fn::GetAtt: [ConfigReceiptTable, Arn]
            - Fn::GetAtt: [BankTable, Arn]
            # Permiss√µes para GSI indexes da UsersTable
            - Fn::Join:
                - "/"
                - - Fn::GetAtt: [UsersTable, Arn]
                  - "index"
                  - "*"
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    CAMPANHA_TABLE: ${self:custom.campanhaTableName}
    DEPOSIT_REQUEST_TABLE: ${self:custom.depositRequestTableName}
    VALIDATION_USER_TABLE: ${self:custom.validationUserTableName}
    DONATION_TABLE: ${self:custom.donationTableName}
    REPORTS_TABLE: ${self:custom.reportsTableName}
    CONFIG_RECEIPT_TABLE: ${self:custom.configReceiptTableName}
    BANK_TABLE: ${self:custom.bankTableName}
    # Cloudflare R2 (S3-compatible) - Use Serverless Dashboard variables ou AWS Systems Manager Parameter Store
    CLOUDFLARE_R2_ACCOUNT_ID: ${param:CLOUDFLARE_R2_ACCOUNT_ID}
    CLOUDFLARE_R2_ACCESS_KEY_ID: ${param:CLOUDFLARE_R2_ACCESS_KEY_ID}
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${param:CLOUDFLARE_R2_SECRET_ACCESS_KEY}
    CLOUDFLARE_R2_BUCKET_NAME: ${param:CLOUDFLARE_R2_BUCKET_NAME}
    CLOUDFLARE_R2_ENDPOINT: ${param:CLOUDFLARE_R2_ENDPOINT}
    CLOUDFLARE_R2_PUBLIC_URL: ${param:CLOUDFLARE_R2_PUBLIC_URL}
    # Mercado Pago
    MERCADO_PAGO_ACCESS_TOKEN: ${param:MERCADO_PAGO_ACCESS_TOKEN}
    MERCADO_PAGO_PUBLIC_KEY: ${param:MERCADO_PAGO_PUBLIC_KEY}
    # URLs
    API_URL: ${param:API_URL}
    FRONTEND_URL: ${param:FRONTEND_URL}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: cpf
            AttributeType: S
          - AttributeName: cnpj
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: cpf-index
            KeySchema:
              - AttributeName: cpf
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: cnpj-index
            KeySchema:
              - AttributeName: cnpj
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.usersTableName}

    CampanhaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: campanha_id
            AttributeType: S
        KeySchema:
          - AttributeName: campanha_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.campanhaTableName}

    DepositRequestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: request_id
            AttributeType: S
        KeySchema:
          - AttributeName: request_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.depositRequestTableName}

    ValidationUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: validation_id
            AttributeType: S
        KeySchema:
          - AttributeName: validation_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.validationUserTableName}

    DonationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: payment_id
            AttributeType: S
        KeySchema:
          - AttributeName: payment_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.donationTableName}

    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: report_id
            AttributeType: S
        KeySchema:
          - AttributeName: report_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.reportsTableName}

    ConfigReceiptTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: receipt_id
            AttributeType: S
        KeySchema:
          - AttributeName: receipt_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.configReceiptTableName}

    BankTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: bank_id
            AttributeType: S
        KeySchema:
          - AttributeName: bank_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.bankTableName}
